### PR TITLE
enable universal wheels

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by jakirkham** [comment]
Would be nice to have the license file included as well.

**Comment by datapythonista** [comment]
Thanks @graingert for the PR!

**Comment by graingert** [comment]
Can we get a release with this in?

**Comment by datapythonista** [comment]
surely at some point, not sure when I'll have the time

**Comment by datapythonista** [comment]
@graingert I just released mnist 0.2.2 which includes the universal wheels. It's in pypi: https://pypi.org/project/mnist/

I also opened a PR to have it available in conda-forge.

**Pull request merged**
